### ISSUE TITLE
Possibility of using this API in an objective-c environment

### ISSUE THREAD

**Issue by unuigbee** [apollostack/apollo-ios#1]
Currently I have an objective-c based project and i'd like use it in my project. I know I can't work with swift structs and enums (unless it's strictly of type int). So i'm wondering how would I go about using this API in my objective-c project?

**Comment by unuigbee** [comment]
It's just a side project btw nothing major.

**Comment by stubailo** [comment]
I think we started with Swift because the type system is more expressive. Some of these concepts could we used in Objective-C as well, but we would need to figure out how to work around some of the limitations of the system.

**Comment by unuigbee** [comment]
Yes Swift seems perfect for working with GraphQL queries and objective-c seems like a major handicap. I guess I might have to create GraphQL strings and send it to the Apollo Server and then traverse the returned JSON data **cries**. I assume I'd have to send this query by POST to the graphQL endpoint.

**Comment by stubailo** [comment]
Yeah, I mean it's not the end of the world though. Eventually we will definitely want to build a great code generation system for Obj-C as well, but we're doing one thing at a time.

**Comment by unuigbee** [comment]
That's great to know. Thanks for taking the time to respond.

**Comment by martijnwalraven** [comment]
Closing this, but note there has been [some activity](https://github.com/apollostack/apollo-codegen/issues/4) on adding an Objective-C target to `apollo-codegen`.
