### ISSUE TITLE
New target for other platforms

### ISSUE THREAD

**Issue by euskadi31** [apollostack/apollo-ios#15]
Hi,

Can you add another targets (tvOS, watchOS and macOS)?

Thx

**Comment by JeroenBe** [comment]
Have a look at issue #10

**Comment by maxsz** [comment]
Thanks for the pull request, was about to do it today, too :)

**Comment by martijnwalraven** [comment]
Closing this, because we now support both iOS and macOS, and also have targets for tvOS and watchOS (untested).
