### ISSUE TITLE
Removing JSON parsing

### ISSUE THREAD

**Issue by lightsprint09** [apollostack/apollo-ios#2]
Would it make sense to remove JSON Parsing at all to concentrate on GraphQL. There are a lot of JSONMappers around and reimplementing them wouldn't make sense.

Think about it. Would like to discuss it 👍

**Comment by stubailo** [comment]
> Would it make sense to remove JSON Parsing at all to concentrate on GraphQL.

Doesn't GraphQL return results in JSON? What would a GraphQL client without JSON parsing do?

**Comment by lightsprint09** [comment]
It does. But what if your implementation returns as Dictionary<String, Any> as result. The Consumer of the can then decide how to parse it. If I find time tomorrow I will add a little example here

**Comment by lightsprint09** [comment]
You only would definde some kind of JSON protocol and the consumer of your API has to implement  it. 

This library could concentate on a great GraphQL implementation and not try to solve JSONMapping 
```swift
protocol JSONInitializable {
  init(map: Dictionary<String, Any>) throws
}
```

```swift
public protocol GraphQLQuery {
  var operationDefinition: String { get }
  var queryDocument: String { get }
  var variables: GraphQLMap? { get }
  
  associatedtype Data: JSONInitializable
}

```

**Comment by mattfxyz** [comment]
Could the JSON deserialization be optional? It's safe to ship with, but it would be nice to have some sort of plug allowing someone to continue using their own deserialization method.

**Comment by lightsprint09** [comment]
I like the idea from @mattfxyz. But this would not remove the overhead of implementing a JSON mapper.

**Comment by martijnwalraven** [comment]
The issue with this is that strictly taken the type system is defined by GraphQL, and JSON is just one [serialization format](https://facebook.github.io/graphql/#sec-Serialization-Format). What that means in practice is that there are GraphQL-specific features that existing JSON mappers don't necessarily support well.

For instance, a GraphQL enum value would be serialized as a JSON string, but as a client you expect an actual enum of the right type to be returned. There are also issues around the handling of optional values. And things quickly get more complicated when you take more advanced GraphQL features into account, like polymorphic results, where a `__typename` field decides what the actual type returned is.

If you're interested, you'll find some more details of the proposed mappings in the [design docs](https://github.com/apollostack/apollo-ios/blob/master/DESIGN.md).

There are probably things that could be be improved about the current implementation of JSON parsing and the resulting mapping, but I feel having this be part of the project offers us more flexibility and is worth the overhead. If we find a good use case for pluggable serialization formats, we can take it from there.
