### ISSUE TITLE
More descriptive errors

### ISSUE THREAD

**Issue by xiekevin** [apollostack/apollo-ios#20]
Right now JSONDecodingError contains why JSON decoding failed but is missing some potentially useful debugging information.

When there is a missing value for a key, it doesn't show you where in the parent JSON the value is missing. Without the parent JSON it's hard to figure out which object is missing the value if you're using the same key in different objects (e.g. id field in two different objects).

Similarly, when an error occurs converting a JSON value to an expected type, it would also be useful to know the key and parent JSON in which the error occurred. Without this information, it's not easy to tell which part of the response was malformed.

Do you think an enhancement to add such information (e.g. key, localized malformed JSON) is possible or useful?

**Comment by martijnwalraven** [comment]
Thanks for opening this issue, and for taking the time to work on a pull request. I completely agree these errors should include the path, and in fact I've already implemented this as part of a more general redesign.

I just released version 0.4.0 of Apollo iOS, which includes the improved error reporting. (You'll also have to update apollo-codegen to 0.9, but it will warn you if you don't.)

Please give it a try and let me know what you think!

**Comment by xiekevin** [comment]
hey martijnwalraven, the changes that were made in 0.4.0 were exactly what I was looking for! The new version is looking great, thank you for your active support on this project.

**Comment by martijnwalraven** [comment]
Good to hear, and keep those issues coming if there is anything else you run into!
