### ISSUE TITLE
Handle @include and @skip directives

### ISSUE THREAD

**Issue by martinohman** [apollostack/apollo-ios#24]
Apollo-ios should handle @include and @skip directives

The following example generates an error when the photos field should be skipped (or not included)
```graphql
query UserQuery($includePhotos: Boolean = true) {
  user {
    ...ProfileFragment
  }
}

fragment ProfileFragment on User {
  id
  photos @include(if: $includePhotos) {
    url
  }
}
```

In the generated code for the above example photos is a non-optional photos property.
```swift
public let photos: [Photo?]
```

When trying to do this query with includePhotos set to false apollo-ios will fail with a GraphQLResultError (underlying Apollo.JSONDecodingError.missingValue)

I believe the expected behavior in this scenario would be making Photos (and any other field that have a @skip or @include directive) an Optional type, in this case:
```swift
public let photos: [Photo?]?
```

**Comment by martijnwalraven** [comment]
I just merged a fix for this to `apollo-codegen`, so updating to 0.9.3 should solve your issue. 

It is not a complete solution yet because it only works when fields have skip or include directives specified, not if you make an entire fragment conditional.

That means this still doesn't work:
```graphql
query UserQuery($includePhotos: Boolean = true) {
  user {
    ...ProfileFragment @include(if: $includePhotos)
  }
}
```
