### ISSUE TITLE
Undeclared type –  GraphQLID

### ISSUE THREAD

**Issue by viniychuk** [apollostack/apollo-ios#3]
Hi guys, 

I've been trying to use MyAPI playground from quick-start package.
I did introspection query and then re-built target and got this error:
http://take.ms/5AFsd
Using latest `apollo-codegen `.

Here's how this field is declared in schema.json:
```
      {
        "kind": "OBJECT",
        "name": "AccessPoint",
        "description": null,
        "fields": [
          {
            "name": "id",
            "description": null,
            "args": [],
            "type": {
              "kind": "SCALAR",
              "name": "ID",
              "ofType": null
            },
            "isDeprecated": false,
            "deprecationReason": null
          },
```

**Comment by martijnwalraven** [comment]
Ah, good catch! I forgot to update the `apollo-ios` submodule dependency in the quickstart when I updated `apollo-codegen`.

If you pull the latest version of `apollo-ios-quickstart` and run `git submodule update --init --recursive` your issue should be fixed.

**Comment by viniychuk** [comment]
@martijnwalraven don't want to upset you, but after I've updated everything I got this – http://take.ms/9yyGl. GrphQLID got fixed tho :) 
p.s. Tried to clean and rebuild, tried making a new clean clone of repo – doesn't help.

**Comment by martijnwalraven** [comment]
Hmmm, this submodule stuff is hard :) I'm working on `apollo-codegen` from master and there have been some changes in the generated code.

I've reverted `apollo-ios` submodule to an earlier version that should still fix the `GraphQLID` issue but work with the released version of `apollo-codegen`.

**Comment by viniychuk** [comment]
@martijnwalraven and.... it works like a charm! And I love it already, it's doing great. Do you think there will be any big changes to the interface anytime soon? I'm about to start using it for the new iOS client (and we're already using `apollo` js client for the web version) 👍

**Comment by martijnwalraven** [comment]
Good to hear!

This is definitely work in progress, but the current interface is pretty minimal, so I don't expect that to change drastically.

I'm currently working on getting fragments and type conditions working, and there will be quiet a few changes to the generated code as a result, but that shouldn't affect the interface.

**Comment by martijnwalraven** [comment]
Closing this, because the issue should be fixed. The [recommended installation steps](http://dev.apollodata.com/ios/installation.html#adding-build-step) now also include a script that checks the installed version of `apollo-codegen` against the Apollo iOS framework version installed in your project.
