### ISSUE TITLE
Query without variables throws fatal error

### ISSUE THREAD

**Issue by rikhub** [apollostack/apollo-ios#35]
My app crashes when I use a query without any variables.
Below you can see my query:

```
query Me {
    me {
        ...UserFragment
    }
}
```

When executing this query I get the following Swift error:

> fatal error: unexpectedly found nil while unwrapping an Optional value

This is happening on line 63 in NetworkTransport.swift where `operation.variables!` is being forcefully unwrapped.
`let stringVar = try! serializationFormat.serialize(value: operation.variables!)`

My workaround is to make an extension for MeQuery and return a empty Dictionary for variables.
```Swift
public extension MeQuery {
    public var variables: GraphQLMap? {
        return [:]
    }
}
```
When I use this extension the query works and the app no longer crashes.

I'm using Apollo 0.4.2 installed with cocoapods.

**Comment by martijnwalraven** [comment]
Could you double check the version of Apollo iOS you have installed?

I can't find the force unwrap that you mention, and [the equivalent line](https://github.com/apollostack/apollo-ios/blob/master/Sources/NetworkTransport.swift#L61) in the current version is:
```swift
let body: GraphQLMap = ["query": type(of: operation).queryDocument, "variables": operation.variables]
```

**Comment by rikhub** [comment]
Thanks for your response. My Podfile was showing the version as 0.4.2 but I did a clean and reinstall and now I see the line of code you mention. So I guess there was a problem on my side somewhere.
Sorry for wasting your time.
