### ISSUE TITLE
GraphQLResponseError not publicly available

### ISSUE THREAD

**Issue by cuva** [apollostack/apollo-ios#38]
I'm currently working with a GraphQL that is protected by an authentication token in the request headers.

I've configured the `HTTPNetworkTransport` to use the token and all works well - except when / if the said token gets invalidated, in which case any subsequent GraphQL request fail with a `GraphQLResponseError`.

The response error does contain the info I need to differentiate an `Unauthorized` error from any other - but as its not publicly declared we can only access its `errorDescription` property via. its `LocalizedError` conformance from outside the Apollo module.

Would it make sense to make `GraphQLResponseError` public, or at least parts of it?

I understand that it may break the encapsulation of future network transports (which probably wouldn't leverage `HTTPURLResponse`).

Of course parsing the errorDescription seems a tad counter-productive here :)

**Comment by cuva** [comment]
I'm happy to submit a PR for the above-mentioned changes once a solution has been discussed / approved.

**Comment by martijnwalraven** [comment]
Maybe we could rename `GraphQLResponseError` to `GraphQLHTTPResponseError` (or just `HTTPResponseError`) before making it public. That way, it is at least clear it is bound to HTTP and wouldn't apply to other transports.

I'd also be interested in exploring a more high level solution to authentication, but this seems like a useful change regardless.
