### ISSUE TITLE
Apollo integration issue

### ISSUE THREAD

**Issue by IvanovDeveloper** [apollostack/apollo-ios#44]
The version of Apollo.framework in your project requires the use of version 0.9 of apollo-codegen, but an unknown older version seems to be installed.

Why it is happened? What I should for resolve this issue?

**Comment by martijnwalraven** [comment]
What version of `apollo-codegen` do you have installed? What does `apollo-codegen --version` return?

You may want to try reinstalling it with `npm install -g apollo-codegen`.

**Comment by IvanovDeveloper** [comment]
npm apollo-codegen --version
2.14.3

**Comment by IvanovDeveloper** [comment]
apollo-codegen --version

/usr/local/lib/node_modules/apollo-codegen/lib/cli.js:33
_process2.default.on('unhandledRejection', error => {
                                                 ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by martijnwalraven** [comment]
It seems you're running an older version of Node, and `apollo-codegen` requires a minimum of Node 4.

I'll make sure to list this in the `package.json` so you would have gotten a more meaningful error message at installation time. Thanks for reporting this!

**Comment by IvanovDeveloper** [comment]
Thanks!

**Comment by IvanovDeveloper** [comment]
also, could you please check this issue
